name: 'AquaCore'
version: 4.5
authors:
  - 'FaceSlap_'
  - 'Activated_'
main: 'me.activated.core.plugin.AquaCore'
description: 'AquaCore made by FaceSlap_ aka Activated_'
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI